[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[window]
padding = { x = 10, y = 0 }

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 14
